### ISSUE TITLE
祝日判定部分のライブラリ化

### ISSUE THREAD

**Issue by akuraru** [fumiyasac/handMadeCalendar#3]
祝日判定部分だけをCocoaPodsにしてほしい。

**Comment by fumiyasac** [comment]
ぜひ前向きに検討したいと思います。
最近はコードなかなか触れていないですが...
まずは、シルバーウィークの判定とゴールデンウイークの判定に改めて間違いがないか再度確認しますね。

**Comment by fumiyasac** [comment]
取り急ぎ下記にSwift版で祝祭日判定部分作った＆テスト書きましたので参考にして頂ければと思います。（CocoaPodsにはしていないけど突っ込めばOKな感じにはしました）
https://github.com/fumiyasac/handMadeCalendarAdvance

Objctive-C版も近く対応しようと思います。

**Comment by akuraru** [comment]
見ておきます

**Comment by fumiyasac** [comment]
今後の予定ですが、
・Swift版CocoaPods化（9月第1週予定）
が直近の予定です。

Swift版が落ち着いたら、
・Objective-C版の祝祭日判定ロジックの見直し→CocoaPods化（11月中までに行う予定）
の流れを予定しております。

**Comment by fumiyasac** [comment]
Swift版CocoaPods化対応完了しました。
https://github.com/fumiyasac/handMadeCalendarAdvance/releases/tag/0.0.2
